version: "3.9"

services:
  category-service:
    build: ./category-service
    ports:
      - 7000:7000
      - 7001:7001
      - 7002:7002
  book-service:
    build: ./book-service
    ports:
    - 8000:8000
    - 8001:8001
    - 8002:8002
  postgres-ps:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data