// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: book-service/book-service.proto

package book_service

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_book_service_book_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_book_service_book_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_book_service_book_service_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type CreateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_book_service_book_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_service_book_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_book_service_book_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBookRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

type CreateBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Book                  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookResponse) Reset() {
	*x = CreateBookResponse{}
	mi := &file_book_service_book_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookResponse) ProtoMessage() {}

func (x *CreateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_service_book_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookResponse.ProtoReflect.Descriptor instead.
func (*CreateBookResponse) Descriptor() ([]byte, []int) {
	return file_book_service_book_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookResponse) GetResult() *Book {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookIds       []int64                `protobuf:"varint,1,rep,packed,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_book_service_book_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_service_book_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_book_service_book_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteBookRequest) GetBookIds() []int64 {
	if x != nil {
		return x.BookIds
	}
	return nil
}

type DeleteBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookResponse) Reset() {
	*x = DeleteBookResponse{}
	mi := &file_book_service_book_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookResponse) ProtoMessage() {}

func (x *DeleteBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_service_book_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return file_book_service_book_service_proto_rawDescGZIP(), []int{4}
}

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookIds       []int64                `protobuf:"varint,1,rep,packed,name=book_ids,json=bookIds,proto3" json:"book_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_book_service_book_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_book_service_book_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_book_service_book_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetBookRequest) GetBookIds() []int64 {
	if x != nil {
		return x.BookIds
	}
	return nil
}

type GetBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookResponse) Reset() {
	*x = GetBookResponse{}
	mi := &file_book_service_book_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookResponse) ProtoMessage() {}

func (x *GetBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_book_service_book_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookResponse.ProtoReflect.Descriptor instead.
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return file_book_service_book_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetBookResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_book_service_book_service_proto protoreflect.FileDescriptor

const file_book_service_book_service_proto_rawDesc = "" +
	"\n" +
	"\x1fbook-service/book-service.proto\x12&daniil4142.book_market.book_service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"K\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\"\\\n" +
	"\x11CreateBookRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x02\x18dR\x04name\x12(\n" +
	"\vcategory_id\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\n" +
	"categoryId\"Z\n" +
	"\x12CreateBookResponse\x12D\n" +
	"\x06result\x18\x01 \x01(\v2,.daniil4142.book_market.book_service.v1.BookR\x06result\"<\n" +
	"\x11DeleteBookRequest\x12'\n" +
	"\bbook_ids\x18\x01 \x03(\x03B\f\xfaB\t\x92\x01\x06\"\x04\"\x02 \x00R\abookIds\"\x14\n" +
	"\x12DeleteBookResponse\"9\n" +
	"\x0eGetBookRequest\x12'\n" +
	"\bbook_ids\x18\x01 \x03(\x03B\f\xfaB\t\x92\x01\x06\"\x04\"\x02 \x00R\abookIds\"U\n" +
	"\x0fGetBookResponse\x12B\n" +
	"\x05books\x18\x01 \x03(\v2,.daniil4142.book_market.book_service.v1.BookR\x05books2\xe1\x03\n" +
	"\vBookService\x12\x9d\x01\n" +
	"\n" +
	"CreateBook\x129.daniil4142.book_market.book_service.v1.CreateBookRequest\x1a:.daniil4142.book_market.book_service.v1.CreateBookResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/books/create\x12\x9d\x01\n" +
	"\n" +
	"DeleteBook\x129.daniil4142.book_market.book_service.v1.DeleteBookRequest\x1a:.daniil4142.book_market.book_service.v1.DeleteBookResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/books/delete\x12\x91\x01\n" +
	"\aGetBook\x126.daniil4142.book_market.book_service.v1.GetBookRequest\x1a7.daniil4142.book_market.book_service.v1.GetBookResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/books/getB\x1fZ\x1dpkg/book-service;book_serviceb\x06proto3"

var (
	file_book_service_book_service_proto_rawDescOnce sync.Once
	file_book_service_book_service_proto_rawDescData []byte
)

func file_book_service_book_service_proto_rawDescGZIP() []byte {
	file_book_service_book_service_proto_rawDescOnce.Do(func() {
		file_book_service_book_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_book_service_book_service_proto_rawDesc), len(file_book_service_book_service_proto_rawDesc)))
	})
	return file_book_service_book_service_proto_rawDescData
}

var file_book_service_book_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_book_service_book_service_proto_goTypes = []any{
	(*Book)(nil),               // 0: daniil4142.book_market.book_service.v1.Book
	(*CreateBookRequest)(nil),  // 1: daniil4142.book_market.book_service.v1.CreateBookRequest
	(*CreateBookResponse)(nil), // 2: daniil4142.book_market.book_service.v1.CreateBookResponse
	(*DeleteBookRequest)(nil),  // 3: daniil4142.book_market.book_service.v1.DeleteBookRequest
	(*DeleteBookResponse)(nil), // 4: daniil4142.book_market.book_service.v1.DeleteBookResponse
	(*GetBookRequest)(nil),     // 5: daniil4142.book_market.book_service.v1.GetBookRequest
	(*GetBookResponse)(nil),    // 6: daniil4142.book_market.book_service.v1.GetBookResponse
}
var file_book_service_book_service_proto_depIdxs = []int32{
	0, // 0: daniil4142.book_market.book_service.v1.CreateBookResponse.result:type_name -> daniil4142.book_market.book_service.v1.Book
	0, // 1: daniil4142.book_market.book_service.v1.GetBookResponse.books:type_name -> daniil4142.book_market.book_service.v1.Book
	1, // 2: daniil4142.book_market.book_service.v1.BookService.CreateBook:input_type -> daniil4142.book_market.book_service.v1.CreateBookRequest
	3, // 3: daniil4142.book_market.book_service.v1.BookService.DeleteBook:input_type -> daniil4142.book_market.book_service.v1.DeleteBookRequest
	5, // 4: daniil4142.book_market.book_service.v1.BookService.GetBook:input_type -> daniil4142.book_market.book_service.v1.GetBookRequest
	2, // 5: daniil4142.book_market.book_service.v1.BookService.CreateBook:output_type -> daniil4142.book_market.book_service.v1.CreateBookResponse
	4, // 6: daniil4142.book_market.book_service.v1.BookService.DeleteBook:output_type -> daniil4142.book_market.book_service.v1.DeleteBookResponse
	6, // 7: daniil4142.book_market.book_service.v1.BookService.GetBook:output_type -> daniil4142.book_market.book_service.v1.GetBookResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_book_service_book_service_proto_init() }
func file_book_service_book_service_proto_init() {
	if File_book_service_book_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_book_service_book_service_proto_rawDesc), len(file_book_service_book_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_book_service_book_service_proto_goTypes,
		DependencyIndexes: file_book_service_book_service_proto_depIdxs,
		MessageInfos:      file_book_service_book_service_proto_msgTypes,
	}.Build()
	File_book_service_book_service_proto = out.File
	file_book_service_book_service_proto_goTypes = nil
	file_book_service_book_service_proto_depIdxs = nil
}
