// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: category-service/category-service.proto

package category_service

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Category with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Category) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Category with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CategoryMultiError, or nil
// if none found.
func (m *Category) ValidateAll() error {
	return m.validate(true)
}

func (m *Category) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	if len(errors) > 0 {
		return CategoryMultiError(errors)
	}

	return nil
}

// CategoryMultiError is an error wrapping multiple validation errors returned
// by Category.ValidateAll() if the designated constraints aren't met.
type CategoryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CategoryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CategoryMultiError) AllErrors() []error { return m }

// CategoryValidationError is the validation error returned by
// Category.Validate if the designated constraints aren't met.
type CategoryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CategoryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CategoryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CategoryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CategoryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CategoryValidationError) ErrorName() string { return "CategoryValidationError" }

// Error satisfies the builtin error interface
func (e CategoryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCategory.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CategoryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CategoryValidationError{}

// Validate checks the field values on GetCategoryByIdRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCategoryByIdRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCategoryByIdRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCategoryByIdRequestMultiError, or nil if none found.
func (m *GetCategoryByIdRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCategoryByIdRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := GetCategoryByIdRequestValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetCategoryByIdRequestMultiError(errors)
	}

	return nil
}

// GetCategoryByIdRequestMultiError is an error wrapping multiple validation
// errors returned by GetCategoryByIdRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCategoryByIdRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCategoryByIdRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCategoryByIdRequestMultiError) AllErrors() []error { return m }

// GetCategoryByIdRequestValidationError is the validation error returned by
// GetCategoryByIdRequest.Validate if the designated constraints aren't met.
type GetCategoryByIdRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCategoryByIdRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCategoryByIdRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCategoryByIdRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCategoryByIdRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCategoryByIdRequestValidationError) ErrorName() string {
	return "GetCategoryByIdRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCategoryByIdRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCategoryByIdRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCategoryByIdRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCategoryByIdRequestValidationError{}

// Validate checks the field values on GetCategoryByIdResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCategoryByIdResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCategoryByIdResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCategoryByIdResponseMultiError, or nil if none found.
func (m *GetCategoryByIdResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCategoryByIdResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCategory()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetCategoryByIdResponseValidationError{
					field:  "Category",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetCategoryByIdResponseValidationError{
					field:  "Category",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCategory()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetCategoryByIdResponseValidationError{
				field:  "Category",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetCategoryByIdResponseMultiError(errors)
	}

	return nil
}

// GetCategoryByIdResponseMultiError is an error wrapping multiple validation
// errors returned by GetCategoryByIdResponse.ValidateAll() if the designated
// constraints aren't met.
type GetCategoryByIdResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCategoryByIdResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCategoryByIdResponseMultiError) AllErrors() []error { return m }

// GetCategoryByIdResponseValidationError is the validation error returned by
// GetCategoryByIdResponse.Validate if the designated constraints aren't met.
type GetCategoryByIdResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCategoryByIdResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCategoryByIdResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCategoryByIdResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCategoryByIdResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCategoryByIdResponseValidationError) ErrorName() string {
	return "GetCategoryByIdResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetCategoryByIdResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCategoryByIdResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCategoryByIdResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCategoryByIdResponseValidationError{}
