// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.17.3
// source: category-service/category-service.proto

package category_service

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_category_service_category_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_category_service_category_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_category_service_category_service_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCategoryByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryByIdRequest) Reset() {
	*x = GetCategoryByIdRequest{}
	mi := &file_category_service_category_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryByIdRequest) ProtoMessage() {}

func (x *GetCategoryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_category_service_category_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryByIdRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryByIdRequest) Descriptor() ([]byte, []int) {
	return file_category_service_category_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetCategoryByIdRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCategoryByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryByIdResponse) Reset() {
	*x = GetCategoryByIdResponse{}
	mi := &file_category_service_category_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryByIdResponse) ProtoMessage() {}

func (x *GetCategoryByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_category_service_category_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryByIdResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryByIdResponse) Descriptor() ([]byte, []int) {
	return file_category_service_category_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetCategoryByIdResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

var File_category_service_category_service_proto protoreflect.FileDescriptor

const file_category_service_category_service_proto_rawDesc = "" +
	"\n" +
	"'category-service/category-service.proto\x12*daniil4142.book_market.category_service.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\".\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"1\n" +
	"\x16GetCategoryByIdRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x02id\"k\n" +
	"\x17GetCategoryByIdResponse\x12P\n" +
	"\bcategory\x18\x01 \x01(\v24.daniil4142.book_market.category_service.v1.CategoryR\bcategory2\xae\x01\n" +
	"\x0fCategoryService\x12\x9a\x01\n" +
	"\x0fGetCategoryById\x12B.daniil4142.book_market.category_service.v1.GetCategoryByIdRequest\x1aC.daniil4142.book_market.category_service.v1.GetCategoryByIdResponseB'Z%pkg/category-service;category_serviceb\x06proto3"

var (
	file_category_service_category_service_proto_rawDescOnce sync.Once
	file_category_service_category_service_proto_rawDescData []byte
)

func file_category_service_category_service_proto_rawDescGZIP() []byte {
	file_category_service_category_service_proto_rawDescOnce.Do(func() {
		file_category_service_category_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_service_category_service_proto_rawDesc), len(file_category_service_category_service_proto_rawDesc)))
	})
	return file_category_service_category_service_proto_rawDescData
}

var file_category_service_category_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_category_service_category_service_proto_goTypes = []any{
	(*Category)(nil),                // 0: daniil4142.book_market.category_service.v1.Category
	(*GetCategoryByIdRequest)(nil),  // 1: daniil4142.book_market.category_service.v1.GetCategoryByIdRequest
	(*GetCategoryByIdResponse)(nil), // 2: daniil4142.book_market.category_service.v1.GetCategoryByIdResponse
}
var file_category_service_category_service_proto_depIdxs = []int32{
	0, // 0: daniil4142.book_market.category_service.v1.GetCategoryByIdResponse.category:type_name -> daniil4142.book_market.category_service.v1.Category
	1, // 1: daniil4142.book_market.category_service.v1.CategoryService.GetCategoryById:input_type -> daniil4142.book_market.category_service.v1.GetCategoryByIdRequest
	2, // 2: daniil4142.book_market.category_service.v1.CategoryService.GetCategoryById:output_type -> daniil4142.book_market.category_service.v1.GetCategoryByIdResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_category_service_category_service_proto_init() }
func file_category_service_category_service_proto_init() {
	if File_category_service_category_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_service_category_service_proto_rawDesc), len(file_category_service_category_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_category_service_category_service_proto_goTypes,
		DependencyIndexes: file_category_service_category_service_proto_depIdxs,
		MessageInfos:      file_category_service_category_service_proto_msgTypes,
	}.Build()
	File_category_service_category_service_proto = out.File
	file_category_service_category_service_proto_goTypes = nil
	file_category_service_category_service_proto_depIdxs = nil
}
