project:
  name: Book MarketPlace
  debug: true
  environment: development

grpc:
  host: 0.0.0.0
  port: 6002
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

gateway:
  host: 0.0.0.0
  port: 6000
  allowedCorsOrigins:
    - "http://localhost:6001"
    - "http://0.0.0.0:6001"
    - "http://127.0.0.1:6001"

swagger:
  host: 0.0.0.0
  port: 6001
  filepath: "swagger/book-service/book-service.swagger.json"

categoryServiceAddr: "http://localhost:8002"
