project:
  name: Category Service
  debug: true
  environment: development

grpc:
  host: 0.0.0.0
  port: 7002
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

gateway:
  host: 0.0.0.0
  port: 7000
  allowedCorsOrigins:
    - "http://localhost:7001"
    - "http://0.0.0.0:7001"
    - "http://127.0.0.1:7001"
    - "http://localhost:8001"
    - "http://0.0.0.0:8001"
    - "http://127.0.0.1:8001"
    - "http://localhost:8002"
    - "http://0.0.0.0:8002"
    - "http://127.0.0.1:8002"
    - "http://localhost:8000"
    - "http://0.0.0.0:8000"
    - "http://127.0.0.1:8000"

swagger:
  host: 0.0.0.0
  port: 7001
  filepath: "swagger/category-service/category-service.swagger.json"
